name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Use the Stellar Group Docker container
    container:
      image: stellargroup/clang_p2996_build_env:1

    steps:
      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-enable: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore xmake packages
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          actions-cache-enable: true
          packages-cache-enable: true
          packages-cache-key: xmake.lua

      - name: Configure and Test
        run: |
          export CXX=clang++
          export CC=clang
          xmake f --root -y
          xmake test -v --root
